version: '3'
services:
  chart:
    restart: always
    build: .
    container_name: 'chart'
    working_dir: '/root/opt'
    tty: true
    ports:
      - 5000:5000
    volumes:
      - ./opt:/root/opt
      #- /home/samba/share/muzinzo:/root/opt/share
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
